### PR TITLE
enable boundaries option as fallback to boundarys, editor config

### PR DESCRIPTION
**Pull request by mubaidr**
This also includes some formatting changes.

### CODE REVIEW

**Comment by Simonwep** [comment]
To the first commit: Please do not change the line-indent. Moreover please run `npm build` on each pull-request (see [CONTRIBUTING.md](https://github.com/Simonwep/selection/blob/master/CONTRIBUTING.md)).

_boundarys_ should be changed to _boundaries_. Thanks, I didn't see that. I will fix that later.
On line `51` (`if (this.options.boundarie`...): should be outside of the for-loop, also i won't you to be able to choose between 'boundaries' or 'boundarys'.

Thanks anyway!

**Comment by mubaidr** [comment]
> boundarys should be changed to boundaries. Thanks, I didn't see that. I will fix that later.
On line 51 (if (this.options.boundarie...): should be outside of the for-loop, also i won't you to be able to choose between 'boundaries' or 'boundarys'.

I have allowed the user to be able to choose between the two, otherwise this scripts will break for the current users. Otherwise it can be just updated to new one. 

Regarding the indent setting, I tried adding editor config, but somehow editor did not picked up my settings. :/ Will try to fix that and will run build command.

**Comment by Simonwep** [comment]
The class string 'selection' shouldn't be hard-coded. Also I want to give the programmer the choice how to allow multi-selection. You simply copy-pasted the code from the demo to the core, this isn't very good. Also what if the user dont want exactly **this** functionality.

**Comment by Simonwep** [comment]
I will close this pull-request, there are to many changes which aren't so nice. if you changed the things which I mentioned above, you can make another _clean_ pull-request. Thanks!

**Pull request closed without merging**
